version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "HomemadeICT"
    labels:
      - "dependencies"
      - "nuget"
    commit-message:
      prefix: "chore"
      prefix-scope: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:30"
    reviewers:
      - "HomemadeICT"
    labels:
      - "ci"
      - "github-actions"
    commit-message:
      prefix: "ci"
      prefix-scope: "github-actions"
      include: "scope"
